apiVersion: v1
kind: Service
metadata:
  name: flask-alpine
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-alpine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-alpine
  namespace: default
  labels:
    app: flask-alpine
spec:
  selector:
    matchLabels:
      app: flask-alpine
      tier: flask-alpine
  template:
    metadata:
        name: flask-alpine
        namespace: default
        labels: 
          app: flask-alpine
          tier: flask-alpine
    spec:
      containers:
      - image: 192.168.99.101:5000/flask-alpine:1
        name: flask-alpine
        ports:
        - containerPort: 80
          name: flask-alpine
